### ISSUE TITLE
Alternative CSS precendence implementation

### ISSUE THREAD

**Issue by robertknight** [js-next/react-style#54]
react-style allows the precedence of styles to be set based on the order they appear in the 'styles' prop for a component.

As I understand it, CSS doesn't support this 'natively' and the implementation uses a hack which generates pretty ugly selectors in order to achieve this (.className .className.className1 ... .className.className1....className9). That ends up being awkward to work with in web inspector etc, just because parts of the UI are not designed with such lengthy selector names in mind. Plus if CSS is being precompiled it will bloat the output.

One alternative might be to compare the sets of properties defined by each of the styles assigned to an element and if there are any conflicts, apply an inline style to the element to set that property. Or perhaps disallow conflicts altogether and require the developer to resolve them via another means. Are there any other approaches that could be taken?

**Comment by daniellewissc** [comment]
regarding pseudo classes, is it the pseudo classes that are the problem, or is it what the pseudo classes individually represent? For instance whats the difference between .classname:hover {} and .classname.hover {} where the element has an event listener that adds and removes the hover class depending on if the mouse is over it? because if there is no difference and the latter still causing issues then i dont think i really understand the issue.

**Comment by SanderSpies** [comment]
Closing this one, old stuff.
